'use strict';
const nodemailer = require('nodemailer');
const sparkPostTransport = require('nodemailer-sparkpost-transport');
var hbs = require('nodemailer-express-handlebars');
const domain = process.env.NODE_ENV === 'production' ? 'https://www.mommymeetups.com/' : 'http://localhost:3001/';

const fromEmail = 'admin@petprenup.com';
var transporter = nodemailer.createTransport(
  sparkPostTransport({
    sparkPostApiKey: process.env.SPARKPOST_API_KEY,
  })
);

if (process.env.NODE_ENV !== 'production') {
  transporter = nodemailer.createTransport({
    host: 'smtp.ethereal.email',
    port: 587,
    auth: {
      user: 'mymwknlnc6wcibr3@ethereal.email',
      pass: '22ygDFjWMxr8AcrXZM',
    },
  });
}

transporter.use(
  'compile',
  hbs({
    viewPath: 'email-templates',
    extName: '.hbs',
  })
);

exports.welcomeEmail = function(user) {
  var userName = user.firstName + ' ' + user.lastName;
  var text = 'Welcome to Mommy Meeetups. Used the link below to signin.';

  let mailOptions = {
    replyTo: '' + userName + '<' + user.email + '>', // sender address
    from: fromEmail,
    to: user.email, // list of receivers
    subject: 'Welcome to Mommy Meeetups', // Subject line
    text: text,
    template: 'email-template',
    context: {
      title: 'Welcome to Mommy Meeetups.',
      content: text,
      linkTitle: 'Sign In',
      url: domain + 'sign-in',
    },
  };

  // send mail with defined transport object
  transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
      console.log(error);
    }
    console.log('Message sent: %s', info.messageId);
    console.log('Preview URL: %s', nodemailer.getTestMessageUrl(info));
  });
};

exports.sendResetPasswordEmail = function(user, token) {
  var userName = user.firstName + ' ' + user.lastName;
  var url = domain + 'reset-password/' + token;
  var text =
    'A reset password email has been generated. Please visit ' +
    url +
    ' to update your password. If this was not generated by you please disregard.';
  var htmlContent =
    'A reset password email has been generated. Please visit the link below to update your password. If this was not generated by you please disregar';

  let mailOptions = {
    replyTo: '' + userName + '<' + user.email + '>', // sender address
    from: fromEmail,
    to: user.email, // list of receivers
    subject: 'Password Reset', // Subject line
    template: 'email-template',
    context: {
      title: 'Reset your Password.',
      content: htmlContent,
      linkTitle: 'Password Reset',
      url: url,
    },
    text: text,
  };

  // send mail with defined transport object
  transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
      console.log(error);
    }
    console.log('Message sent: %s', info.messageId);
    console.log('Preview URL: %s', nodemailer.getTestMessageUrl(info));
  });
};
